# Generated by Django 3.0.5 on 2020-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='init_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
